services:
  office-attendance:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src:/home/node/src
      - ./public:/home/node/public
      - ./package.json:/home/node/package.json
