{{- define "dream-league-web.container" -}}
envFrom:
- configMapRef:
    name: {{ .Values.name }}
ports:
- containerPort: {{ .Values.container.port }}
  name: http
  protocol: TCP
volumeMounts:
  - mountPath: /home/node/app/build
    name: build-dir
{{- end -}}
