{{- define "dream-league-web.container" -}}
envFrom:
- configMapRef:
    name: {{ .Values.name }}
ports:
- containerPort: {{ .Values.container.port }}
  name: http
  protocol: TCP
volumeMounts:
  - mountPath: /home/node/build
    name: npm-cache-dir
  - mountPath: /home/node/node_modules/.cache
    name: build-dir
  - mountPath: /tmp
    name: tmp-dir
{{- end -}}
