{{- include "helm-library.deployment" (list . "dream-league-web.deployment") -}}
{{- define "dream-league-web.deployment" -}}
spec:
  template:
    spec:
      volumes:
      - name: build-dir
        emptyDir: {}
      - name: tmp-dir
        emptyDir: {}
      containers:
      - {{ include "helm-library.container" (list . "dream-league-web.container") }}
{{- end -}}
