const options = [
  'No',
  'Not today',
  'Nope',
  'Stay home',
  'Not a chance',
  'Not this time',
  'Weather doesn\'t look good, stay home',
  'No, stay home',
  'Better not today',
  'The stars say no',
  'You\'ll regret it if you go',
  'What\'s the point?',
  'Please stay home',
  'Bad things will happen if you go',
  '100% no',
  'Absolutely not',
  'Under no circumstances',
  'I\'d strongly discourage it',
  'It\'s a terrible idea',
  'I advise against it',
  'I highly recommend staying home',
  'It\'s not worth the risk',
  'Definitely not today',
  'The answer is a firm no',
  'It\'s a definite no-go',
  'No way, no how',
  'Seriously reconsider going out',
  'Stay home, it\'s safer',
  'Not advisable at all',
  'I wouldn\'t risk it',
  'Maybe tomorrow',
  'Try again tomorrow',
  'Ask again tomorrow',
  'Maybe another day',
  'Not today, maybe tomorrow',
  'You\'ve been too recently, so no',
  'You\'re joking, right?',
  'You\'re joking me, you gotta be',
  'Haha, no',
  'I wouldn\'t go if I were you',
  'I wouldn\'t risk it',
  'It\'s not worth it',
  'You\'ll get sick if you go',
  'Stay home',
  'It\'s not the right time',
  'Think about it again tomorrow',
  'The timing is off',
  'Not today, maybe next time',
  'Perhaps reconsider later',
  'The signs point to no',
  'The universe says no',
  'Chances are slim',
  'Take a rain check',
  'Consider staying in',
  'Think twice before going',
  'Better off staying put',
  'It\'s a no-win situation',
  'Not advisable right now',
  'I strongly advise staying put',
  'Safety first, stay home',
  'Better safe than sorry, so stay home',
  'Avoid unnecessary risks',
  'Stay in your comfort zone',
  'Stay within your safe space',
  'Consider your health first, remain indoors',
  'Your best bet is to stay home',
  'It\'s a risk not worth taking',
  'Better off indoors',
  'The odds aren\'t in your favour',
  'It\'s a negative outlook',
  'Your gut feeling says no',
  'Listen to your instincts, stay home',
  'I\'d bet against it',
  'It\'s a definite no-no',
  'Avoid the outside world',
  'The circumstances aren\'t favourable',
  'Stay where you\'re safest, here',
  'I\'d lean towards not going',
  'It\'s not a good idea, trust me',
  'I\'d strongly dissuade going out',
  'Stay away from unnecessary trouble',
  'It\'s a negative outcome waiting',
  'Not a good time to venture out',
  'The chances are remote',
  'It\'s a no-brainer, stay home',
  'It\'s better to play it safe',
  'You\'re better off staying inside',
  'Don’t risk it, stay home',
  'The odds of success are low',
  'The risks outweigh the benefits',
  'Stay within your comfort zone',
  'That person you don\'t like might be there',
  'You\'ll probably regret it if you go',
  'That\'s the worst idea I\'ve ever heard',
  'That\'s what I\'d call a bad idea',
  'Stay within your safe space',
  'What\'s the point?',
  'Why bother?',
  'That\'s a negative',
  'I wouldn\'t count on it',
  'My reply is no',
  'My sources say no',
  'Outlook not so good',
  'Very doubtful'
]

export default options
